name: flutter_text_utils_example
description: Example app for flutter_text_utils
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_text_utils:
    path: ../  # points to your package root
